open_recipe_by_voice:
  fields:
    text:
      required: true
      example: dahl de lentilles
      selector:
        text:
    browser_id:
      example: kitchen_tablet
      selector:
        text:
    dashboard_path:
      example: /dashboard-kitchen/recipes
      selector:
        text:
